{{- if index $.Values "apps" "keycloak" "enabled" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: keycloak-operator
  namespace: argocd
spec:
  project: default
  source:
    path: deploy
    repoURL: https://github.com/keycloak/keycloak-operator.git
    targetRevision: 13.0.1
  destination:
    namespace: keycloak
    server: {{ .Values.spec.destination.server }}
  {{- if .Values.spec.syncPolicy }}
  syncPolicy:
    {{ toYaml .Values.spec.syncPolicy | nindent 4 }}
  {{- end }}
{{- end }}
